export const REPO_URL = import.meta.env.VITE_APP_REPO_URL ?? "https://github.com/SeanCassiere/nv-reservation-cc-update";
export const SuccessImgUri = "/assets/undraw_make_it_rain_iwk4.svg";
export const APP_CONSTANTS = {
  REF_TYPE_AGREEMENT: "Agreement",
  REF_TYPE_RESERVATION: "Reservation",

  FLOW_CREDIT_CARD_FORM: "CreditCardForm",
  FLOW_DEFAULT_LICENSE_UPLOAD_FORM: "LicenseUploadForm",
  FLOW_CREDIT_CARD_LICENSE_UPLOAD_FORM: "CreditCardAndLicenseUploadForm",
  FLOW_RENTAL_SIGNATURE_FORM: "RentalSignatureForm",
  FLOW_RENTAL_CHARGES_FORM: "RentalSummaryForm",
  FLOW_DEV_SCREEN_1: "DevScreen1",
  FLOW_DEV_SCREEN_2: "DevScreen2",
  FLOW_FORMS_SUMMARY: "FormSummary",

  SUCCESS_DEFAULT: "SuccessSubmission",
  SUCCESS_RENTAL_CHARGES_SUMMARY: "SuccessRentalChargesSummary",
  SUCCESS_SUBMITTED_FORMS_SUMMARY: "SuccessSubmittedFormsSummary",
  SUCCESS_SUBMITTED_FORMS_WITH_RENTAL_CHARGES_SUMMARY: "SuccessSubmittedFormsWithRentalChargesSummary",
  SUCCESS_TEST: "test/test",

  FORM_SUMMARY_OFF: "off",

  THEME_DEFAULT_CLASS: "",
  THEME_DARK_CLASS: "dark",
} as const;

export const ALL_THEME_CLASS_NAMES = [APP_CONSTANTS.THEME_DEFAULT_CLASS, APP_CONSTANTS.THEME_DARK_CLASS];

export const COMPAT_KEYS = {
  DEFAULT_CREDIT_CARD_LICENSE_UPLOAD_FORM: "Default/CreditCardAndLicenseUploadForm",
  DEFAULT_CREDIT_CARD_LICENSE_UPLOAD_CONTROLLER: "Default/CreditCardAndLicenseUploadController",
  DEFAULT_LICENSE_UPLOAD_FORM: "Default/LicenseUploadForm",
  DEFAULT_CREDIT_CARD_FORM: "Default/CreditCardForm",
  DEFAULT_RENTAL_CHARGES_FORM: "Default/RentalSummaryForm",
  DEFAULT_RENTAL_SIGNATURE_FORM: "Default/RentalSignatureForm",

  SUCCESS_RENTAL_SUMMARY: "SuccessRentalSummary",
};

export const ALL_SCREEN_FLOWS = [
  {
    label: APP_CONSTANTS.FLOW_CREDIT_CARD_FORM,
    value: APP_CONSTANTS.FLOW_CREDIT_CARD_FORM,
  },
  {
    label: APP_CONSTANTS.FLOW_DEFAULT_LICENSE_UPLOAD_FORM,
    value: APP_CONSTANTS.FLOW_DEFAULT_LICENSE_UPLOAD_FORM,
  },
  {
    label: APP_CONSTANTS.FLOW_CREDIT_CARD_LICENSE_UPLOAD_FORM,
    value: APP_CONSTANTS.FLOW_CREDIT_CARD_LICENSE_UPLOAD_FORM,
  },
  {
    label: APP_CONSTANTS.FLOW_RENTAL_SIGNATURE_FORM,
    value: APP_CONSTANTS.FLOW_RENTAL_SIGNATURE_FORM,
  },
  {
    label: APP_CONSTANTS.FLOW_RENTAL_CHARGES_FORM,
    value: APP_CONSTANTS.FLOW_RENTAL_CHARGES_FORM,
  },
  {
    label: APP_CONSTANTS.FLOW_DEV_SCREEN_1,
    value: APP_CONSTANTS.FLOW_DEV_SCREEN_1,
  },
  {
    label: APP_CONSTANTS.FLOW_DEV_SCREEN_2,
    value: APP_CONSTANTS.FLOW_DEV_SCREEN_2,
  },
];

export const ALL_SUCCESS_SCREENS = [
  {
    label: APP_CONSTANTS.SUCCESS_TEST,
    value: APP_CONSTANTS.SUCCESS_TEST,
  },
  {
    label: APP_CONSTANTS.SUCCESS_DEFAULT,
    value: APP_CONSTANTS.SUCCESS_DEFAULT,
  },
  {
    label: APP_CONSTANTS.SUCCESS_RENTAL_CHARGES_SUMMARY,
    value: APP_CONSTANTS.SUCCESS_RENTAL_CHARGES_SUMMARY,
  },
  {
    label: APP_CONSTANTS.SUCCESS_SUBMITTED_FORMS_SUMMARY,
    value: APP_CONSTANTS.SUCCESS_SUBMITTED_FORMS_SUMMARY,
  },
  {
    label: APP_CONSTANTS.SUCCESS_SUBMITTED_FORMS_WITH_RENTAL_CHARGES_SUMMARY,
    value: APP_CONSTANTS.SUCCESS_SUBMITTED_FORMS_WITH_RENTAL_CHARGES_SUMMARY,
  },
];
