export const SUBMITTING_FORM_LOADING = "SUBMITTING_FORM_LOADING";
export const SUBMITTING_FORM_ERROR = "SUBMITTING_FORM_ERROR";
export const SUBMITTING_FORM_SUCCESS = "SUBMITTING_FORM_SUCCESS";

export const AUTH_RESERVATION_LOADING = "AUTH_RESERVATION_LOADING";
export const AUTH_RESERVATION_ERROR = "AUTH_RESERVATION_ERROR";
export const AUTH_RESERVATION_SUCCESS = "AUTH_RESERVATION_SUCCESS";
